---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ember-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: example.ember-csi.io
