apiVersion: ember-csi.io/v1alpha1
kind: EmberStorageBackend
metadata:
  name: example
spec:
  config:
    envVars:
      X_CSI_BACKEND_CONFIG:
        driver: HPELeftHandISCSI
        enable_unsupported_driver: false
        hpelefthand_api_url: ''
        hpelefthand_clustername: ''
        hpelefthand_debug: false
        hpelefthand_iscsi_chap_enabled: false
        hpelefthand_password: ''
        hpelefthand_ssh_port: 16022
        hpelefthand_username: ''
        name: ''
      X_CSI_DEBUG_MODE: ''
      X_CSI_DEFAULT_MOUNT_FS: ext4
      X_CSI_EMBER_CONFIG:
        debug: false
        disable_logs: false
        disabled: []
        enable_probe: false
        grpc_workers: 30
        plugin_name: ''
        project_id: ember_csi.io
        slow_operations: true
        user_id: ember_csi.io
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
    sysFiles:
      name: ''
