apiVersion: ember-csi.io/v1alpha1
kind: EmberStorageBackend
metadata:
  name: example
spec:
  config:
    envVars:
      X_CSI_BACKEND_CONFIG:
        driver: LinstorIscsi
        enable_unsupported_driver: false
        linstor_autoplace_count: 0
        linstor_controller_diskless: true
        linstor_default_blocksize: 4096
        linstor_default_storage_pool_name: DfltStorPool
        linstor_default_uri: linstor://localhost
        linstor_default_volume_group_name: drbd-vg
        linstor_volume_downsize_factor: '4096'
        name: ''
      X_CSI_DEBUG_MODE: ''
      X_CSI_DEFAULT_MOUNT_FS: ext4
      X_CSI_EMBER_CONFIG:
        debug: false
        disable_logs: false
        disabled: []
        enable_probe: false
        grpc_workers: 30
        plugin_name: ''
        project_id: ember_csi.io
        slow_operations: true
        user_id: ember_csi.io
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
    sysFiles:
      name: ''
