apiVersion: ember-csi.io/v1alpha1
kind: EmberStorageBackend
metadata:
  name: example
spec:
  config:
    envVars:
      X_CSI_BACKEND_CONFIG:
        driver: VZStorage
        enable_unsupported_driver: false
        name: ''
        vzstorage_default_volume_format: raw
        vzstorage_mount_options: ''
        vzstorage_mount_point_base: $state_path/mnt
        vzstorage_shares_config: /etc/cinder/vzstorage_shares
        vzstorage_sparsed_volumes: true
        vzstorage_used_ratio: '0.95'
      X_CSI_DEBUG_MODE: ''
      X_CSI_DEFAULT_MOUNT_FS: ext4
      X_CSI_EMBER_CONFIG:
        debug: false
        disable_logs: false
        disabled: []
        enable_probe: false
        grpc_workers: 30
        plugin_name: ''
        project_id: ember_csi.io
        slow_operations: true
        user_id: ember_csi.io
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
    sysFiles:
      name: ''
