apiVersion: ember-csi.io/v1alpha1
kind: EmberStorageBackend
metadata:
  name: example
spec:
  config:
    envVars:
      X_CSI_BACKEND_CONFIG:
        driver: XtremIOISCSI
        driver_ssl_cert_path: ''
        driver_ssl_cert_verify: false
        enable_unsupported_driver: false
        name: ''
        san_ip: ''
        san_login: admin
        san_password: ''
        xtremio_array_busy_retry_count: 5
        xtremio_array_busy_retry_interval: 5
        xtremio_clean_unused_ig: false
        xtremio_cluster_name: ''
      X_CSI_DEBUG_MODE: ''
      X_CSI_DEFAULT_MOUNT_FS: ext4
      X_CSI_EMBER_CONFIG:
        debug: false
        disable_logs: false
        disabled: []
        enable_probe: false
        grpc_workers: 30
        plugin_name: ''
        project_id: ember_csi.io
        slow_operations: true
        user_id: ember_csi.io
      X_CSI_PERSISTENCE_CONFIG:
        storage: crd
    sysFiles:
      name: ''
